#!/bin/bash

if [ "${1}" = "-c" ]; 
	then
		g++ driver.cpp tree_nodes.cpp lexer.cpp parser.cpp -o math
else
	mkdir generated	

	flex --stdinit -o generated/lexer.c lexer.inp
	yacc -di -o generated/parser.c grammar.inp
fi
